### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by FireStreaker2** [InterlakeProgrammingClub/ihsClubSite#5]
# main
- [x] main pages
- [x] custom color palette 
- [x] more animations
- [x] setup domain name
- [x] actual club pages
- [x] migrate ``/clubs/[club]`` to ``/[club]``
- [x] add better metadata (ex. title)
- [x] better accessibility 
- [x] fix any other issues we encounter 

# specific issues
- [x] resize images when screen size is smaller than usual
- [x] fix navbar going down a bit on mobile devices (at least according to chrome devtools)
- [x] fix css transition on navbar

# extra
we'll only do these if we have extra time
- [x]  <del>dark mode </del> cancelled

ill periodically update this when we finish stuff and/or need to add more things
